language: python
python:
    - "nightly"
    - 3.6
    - 3.7
sudo: false
install:
    - pip install --upgrade pip
    - pip install https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip
    - pip install .
    - export MPLBACKEND=agg
script:
    - python -m unittest hyperspy_gui_traitsui.test_import
matrix:
    allow_failures:
        - python: "nightly"
