name: Release
# This workflow builds the wheels "on tag".
# If run from the hyperspy/hyperspy_gui_traitsui repository, the wheels will be
# uploaded to pypi; otherwise, the wheels will be available as a github artifact.
# This workflow overwrite the version in `hyperspy_gui_traitsui/version.py`
# with the tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Get version (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

  build_wheels_linux:
    name: Wheels on ubuntu-latest
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install release dependencies
        run: |
          python -m pip install twine wheel

      - name: Overwrite `version.py` with tag
        if: startsWith(github.ref, 'refs/tags/')
        env: 
          version_file: hyperspy_gui_traitsui/version.py
          VERSION: ${{ needs.create_release.outputs.VERSION }}
        run: |
          echo '__version__ = "${{ env.VERSION }}"' > ${{ env.version_file }}

      - name: Build source distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Display content dist folder
        run: |
          ls dist/

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz

      - name: 'Install Ubuntu packages for Qt'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0

      - name: Install Dependencies
        run: |
          pip install pyqt5

      - name: Install package
        env:
          MPLBACKEND: agg
        run: |
          pip install --find-links dist hyperspy_gui_traitsui[tests]

      - name: Run test suite
        # run the tests headlessly
        run: |
          sudo apt-get install xvfb
          xvfb-run pytest --pyargs hyperspy_gui_traitsui

      - name: Publish wheels to PyPI
        if: github.repository_owner == 'hyperspy'
        env:
          # Github secret set in the hyperspy/hyperspy_gui_traitsui repository
          # Not available from fork or pull request
          # Secrets are not passed to workflows that are triggered by a pull request from a fork
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*.whl --verbose 
          twine upload dist/*.tar.gz --verbose 

